platform :ios, '11.0'
use_frameworks!

target 'localstorage' do
  pod 'Charts'
  #pod 'SSZipArchive'
end

target 'Hash' do
    pod 'CommonCryptoModule'
end

target 'Unzip' do
    pod 'SWCompression'
end
