platform :ios, '11.0'
use_frameworks!

target 'localstorage' do
  pod 'Charts'
  pod 'SWCompression'
  pod 'SWCompression/BZip2'
  pod 'SWCompression/Deflate'
  pod 'SWCompression/LZMA'
  pod 'YMTreeMap'
end

target 'Hash' do
    pod 'CommonCryptoModule'
end
